/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package todolist;

import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


 *
 * @author Aluno
 */
public class TelaToDoList extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaToDoList.class.getName());

    DefaultTableModel model; 
    
    private static final String CONCLUIDA = "Concluida";
    private static final String NAO_CONCLUIDA = "nao concluida";
    
    private final ArrayList<String> tarefas = new ArrayList<>();
    private final ArrayList<String> tarefasfiltradas = new ArrayList<>();
    
    public TelaToDoList(JButton jButtonAdicionarTarefa, JButton jButtonConcluirTarefa, JButton jButtonRemoverTarefa, JComboBox<String> jComboBoxFiltroStatus, JScrollPane jScrollPane1, JTable jTableTarefas, JTextField jTextFieldDescricaoTarefa) throws HeadlessException {
        this.opcao = jComboBoxFiltroStatus;
        this.jButtonAdicionarTarefa = jButtonAdicionarTarefa;
        this.jButtonConcluirTarefa = jButtonConcluirTarefa;
        this.jButtonRemoverTarefa = jButtonRemoverTarefa;
        this.jComboBoxFiltroStatus = jComboBoxFiltroStatus;
        this.jScrollPane1 = jScrollPane1;
        this.jTableTarefas = jTableTarefas;
        this.jTextFieldDescricaoTarefa = jTextFieldDescricaoTarefa;
    }
     
    /**
     * Creates new form TelaToDoList
     */
    public TelaToDoList() {
        this.opcao = jComboBoxFiltroStatus;
        initComponents();
        
        setLocationRelativeTo(null);
        
        model = (DefaultTableModel) jTableTarefas.getModel();
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAdicionarTarefa = new javax.swing.JButton();
        jComboBoxFiltroStatus = new javax.swing.JComboBox<>();
        jTextFieldDescricaoTarefa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTarefas = new javax.swing.JTable();
        jButtonRemoverTarefa = new javax.swing.JButton();
        jButtonConcluirTarefa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonAdicionarTarefa.setText("Adicionar");
        jButtonAdicionarTarefa.addActionListener(this::jButtonAdicionarTarefaActionPerformed);

        jComboBoxFiltroStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "concluido", "não concluido" }));
        jComboBoxFiltroStatus.addActionListener(this::jComboBoxFiltroStatusActionPerformed);

        jTableTarefas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tarefa", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableTarefas);
        if (jTableTarefas.getColumnModel().getColumnCount() > 0) {
            jTableTarefas.getColumnModel().getColumn(0).setResizable(false);
            jTableTarefas.getColumnModel().getColumn(1).setResizable(false);
        }

        jButtonRemoverTarefa.setText("Remover");
        jButtonRemoverTarefa.addActionListener(this::jButtonRemoverTarefaActionPerformed);

        jButtonConcluirTarefa.setText("Concluir");
        jButtonConcluirTarefa.addActionListener(this::jButtonConcluirTarefaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldDescricaoTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAdicionarTarefa))
                            .addComponent(jComboBoxFiltroStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonConcluirTarefa)
                .addGap(18, 18, 18)
                .addComponent(jButtonRemoverTarefa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdicionarTarefa)
                    .addComponent(jTextFieldDescricaoTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBoxFiltroStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRemoverTarefa)
                    .addComponent(jButtonConcluirTarefa))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxFiltroStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFiltroStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFiltroStatusActionPerformed

    private void jButtonConcluirTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConcluirTarefaActionPerformed
        int linhaSelecionada = jTableTarefas.getSelectedRow();
        
        if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(null, "Nenhuma tarefa foi seleciona !"); {
            
            
             String tarefaSelecionada = recuperarTarefa(linhaSelecionada);
    
    int indiceTarefaSelecionada = tarefas.indexOf(tarefaSelecionada);
    
    String[] dados = tarefas.get(indiceTarefaSelecionada) . split (";");
    
    tarefas.set(indiceTarefaSelecionada,dados[0] + ";" + CONCLUIDA);
    
    filtrarTabela();
    
    
    preencherTabela();
    
    
        }
            return; 
        }
       
     
    }//GEN-LAST:event_jButtonConcluirTarefaActionPerformed

   
    private void jButtonAdicionarTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarTarefaActionPerformed
       
        
        if (jTextFieldDescricaoTarefa.getText().trim().isEmpty() ) { 
            JOptionPane.showMessageDialog(null, "A descricao da tarefa nao pode ser vazia!");
            return; 
            
            
            
            }
           if (hasTarefaRepetida(jTextFieldDescricaoTarefa.getText())){
             JOptionPane.showMessageDialog(null,  "A tarefa " + jTextFieldDescricaoTarefa.getText() + "ja existe");
             return;
        }
       tarefas.add(jTextFieldDescricaoTarefa.getText() + ";" + NAO_CONCLUIDA);
       
       PreencherTabela(); 
           
    }//GEN-LAST:event_jButtonAdicionarTarefaActionPerformed

    private void jButtonRemoverTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverTarefaActionPerformed
        int linhaSelecionada = jTableTarefas.getSelectedRow();
        
         if (linhaSelecionada < 0) {
             JOptionPane.showMessageDialog(null, "Nenhuma tarefa foi selecionada");
             return; 
             
             
             
             
         }
         
         int opcao = JOptionPane.showConfirmDialog(null,  "Deseja realmente excuir a tarefa?");
         
         String tarefaSelecionada = recuperarTarefa (linhaSelecionada); 
         
              int indiceTarefaSelecionada = tarefas.indexOf(tarefaSelecionada);
              
              if (opcao == JOptionPane.YES_OPTION) {
                  tarefas.remove (indiceTarefaSelecionada);
                  preencherTabela(); 
                  
              }
              
              filtrarTabela(); 
              
              preencherTabela(); 
              
              
              
              
             
              
                 
    }//GEN-LAST:event_jButtonRemoverTarefaActionPerformed
    
    private void filtrarTabela
        int opcao = jComboBoxFiltroStatus.getSelectedIndex();
         tarefasFiltradas.clear();
         
         
         
         String[] dados; 
         
         
         
         for(String tarefa : tarefas){
         
  

    
    
    
    
    
    
    
    private String recuperarTarefa ( int indiceTarefa){
        if (jComboBoxFiltroStatus.getSelectedIndex() > 0) {
             return
        }
        
    }
    
    
    
    public boolean hasTarefaRepetida (String novaTarefa){ 
        for (String tarefa : tarefas) {
            String dados [] = tarefa.split(";");
                    
            if (novaTarefa.toLowerCase().equals(dados [0].toLowerCase())){
                return true;
            }
}
        
        return false;
        
  
    } 
    private void preencherTabela(){
            ArrayList<String>listaTarefas;
            
            if(jComboBoxFiltroStatus.getSelectedIndex() > 0){ 
                ArrayList<String> tarefasFiltradas = null;
                listaTarefas = tarefasFiltradas; 
            } else{
                listaTarefas = tarefas;
            }
            
            model.setRowCount(0);
        Iterable<String> listatarefas = null;
            
            for (String tarefa : listatarefas) {
   
      String[] dados = tarefa.split(";");
           
            model.addRow(new Object[]{
                dados[0],
                dados[1]
            });
           
        }
    }       
        
     
    
    
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaToDoList().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionarTarefa;
    private javax.swing.JButton jButtonConcluirTarefa;
    private javax.swing.JButton jButtonRemoverTarefa;
    private javax.swing.JComboBox<String> jComboBoxFiltroStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTarefas;
    private javax.swing.JTextField jTextFieldDescricaoTarefa;
    // End of variables declaration//GEN-END:variables

    private void PreencherTabela() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
